name: s3-upload

on: 
  workflow_dispatch:

jobs:
  deploy:
    name: DVC Pull from AWS S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ASIA2ORLIS62AINQUIIZ
        aws-secret-access-key: GtKBkgg/VyDTykVxYGSRiXFY7ZbogYZUeonNp//r
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::718424020916:user/jp
        role-external-id: jp
        role-duration-seconds: 1200
        role-session-name: jpSession
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 cp s3://udacity-mldevops-project-3/12/12/616387ced8db7ae66cf8f123ffc48d data/
